//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class studentEntities : DbContext
    {
        public studentEntities()
            : base("name=studentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student_Payments> Student_Payments { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<setting> settings { get; set; }
        public virtual DbSet<student_files> student_files { get; set; }
    }
}
