//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public string StudentSurName { get; set; }
        public string mr_mrs { get; set; }
        public string StudentSchool { get; set; }
        public string StudentBirthDate { get; set; }
        public string StudentBirthPlace { get; set; }
        public string StudentExtraInfo { get; set; }
        public string Adres { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> StudentPrice { get; set; }
        public Nullable<int> StudentRestPrice { get; set; }
        public bool Active { get; set; }
        public bool StudentPapier { get; set; }
        public string AdresPLZ { get; set; }
        public string AdresCity { get; set; }
    }
}
