//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_files
    {
        public int id { get; set; }
        public int studentId { get; set; }
        public string filepath { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string fileName { get; set; }
        public string fileNameOld { get; set; }
    }
}
