//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Payments
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Payment { get; set; }
        public string PaymentDesc { get; set; }
        public bool isDeleted { get; set; }
    }
}
